var Eight = 8;
var twenty = 20;
console.log("\nThese below are true tests:");
console.log("Test 1: Is Eight equal to 8?");
console.log(Eight == 8);
console.log("\nTest 2: is Twenty equal to 20?");
console.log(twenty == 20);
console.log("\nTest 3: Eight is not equal to twenty?");
console.log(Eight != 20);
console.log("\nTest 4: Twenty is greater than Eight?");
console.log(twenty > 8);
console.log("\nTest 5: Eight is less than twenty?");
console.log(Eight < 20);
console.log("\nBelow are false tests:");
console.log("Test 6: Eight is not equal to 8?");
console.log(Eight != 8);
console.log("\nTest 7: Twenty is not equal to 20?");
console.log(twenty != 20);
console.log("\nTest 8: Eight is equal to twenty?");
console.log(Eight == 20);
console.log("\nTest 9: Eight is greater than twenty?");
console.log(Eight > 20);
console.log("\nTest 10: Twenty is less than Eight?");
console.log(twenty < 8);
